version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
      #- image: cimg/base:2020.01  
    steps:
      - checkout
      - run:
          name: "echo variable de entorno solicitado en el ejercicio"
          command: |
            echo $MY_ENV_VAR
workflows:
  test-env-vars:
    jobs:
     - build

